### PR TITLE
Import of rebalance OS script

### PR DESCRIPTION
**Pull request by remibergsma**
It's WIP and only displays what it could be doing. No actual stuff happens.

Ping @lttmtins If you want to continue working on this, switch to the 'os_preference' branch. You can push to it as well so we can work on it together.

### CODE REVIEW

**Comment by lttmtins** [comment]
Succesfully used this branch to list what's needed. Will continue to work on it. 
This particular pull request could be merged already, shall I already merge it?

**Comment by remibergsma** [comment]
Ah, forgot I had done this already :-) I'd say let's merge it when it actually works? You can work on the `os_preference` branch. Simply `git push origin os_preference` and they will end up here.

**Comment by lttmtins** [comment]
Still had to use the merge button to get it in.

**Comment by remibergsma** [comment]
@lttmtins merging wasn't necessary but anyway. Show you next time :-) Master branch is supposed to be stable, shouldn't have work-in-progress stuff. Please do not push to master directly when you continue working on it.

**Pull request merged**
